backend/controllers/RoleController.php
<?php

namespace backend\controllers;

use backend\models\forms\RoleForm;
use common\components\controllers\WebController;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\rbac\DbManager;
use yii\rbac\Item;

/**
 * Class RolesController
 *
 * @author Andreev Sergey <si.andreev316@gmail.com>
 * @version 1.0
 */
class RoleController extends WebController
{
    const ADMIN_ROLE = 'admin';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index'],
                        'roles'   => ['backend/users/roles/view'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['edit'],
                        'roles'   => ['backend/users/roles/edit'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Roles with theirs permissions.
     * @return mixed
     */
    public function actionIndex()
    {
        /** @var DbManager $authManager */
        $authManager = Yii::$app->authManager;

        $rolesQuery = (new Query)
            ->select(['id' => 'r.name', 'roleName' => 'r.name'])
            ->from(['r' => $authManager->itemTable])
            ->andWhere(['r.type' => Item::TYPE_ROLE]);
        $rolesData = new ActiveDataProvider([
            'query' => $rolesQuery
        ]);

        return $this->render('index', [
            'dataProvider' => $rolesData,
        ]);
    }


    /**
     * @param $name
     * @return mixed
     */
    public function actionEdit($name)
    {
        $model = new RoleForm(['scenario' => RoleForm::SCENARIO_UPDATE]);

        /** @var DbManager $authManager */
        $authManager = Yii::$app->authManager;

        $role = $authManager->getRole($name);
        $model->setRole($role);

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('edit', [
                'model' => $model,
                'role'  => $role
            ]);
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\forms\UserForm;
use backend\models\search\UserSearch;
use common\components\controllers\WebController;
use common\models\user\Status;
use Yii;
use common\models\user\User;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends WebController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'view'],
                        'roles'   => ['backend/users/accounts/view']
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['create'],
                        'roles'   => ['backend/users/accounts/create']
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['update', 'confirm', 'ban', 'lift-ban'],
                        'roles'   => ['backend/users/accounts/edit']
                    ]
                ]
            ]
        ];
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays a single User model.
     *
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new UserForm(['scenario' => UserForm::SCENARIO_CREATE]);

        if ($model->load(Yii::$app->request->post()) && $model->create()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = new UserForm(['scenario' => UserForm::SCENARIO_UPDATE]);
        $user = $this->findModel($id);
        $model->setUser($user);

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model
            ]);
        }
    }

    public function actionConfirm($id)
    {
        $model = User::find()->hasId($id)->one();

        if (!empty($model)) {
            $model->status = Status::active();
            $model->save();
        }

        $this->redirect(['view', 'id' => $id]);
    }

    public function actionBan($id)
    {
        $model = User::find()->hasId($id)->notBanned()->one();

        if (!empty($model)) {
            $model->status = Status::inactive();
            $model->save();
        }

        $this->redirect(['view', 'id' => $id]);
    }

    public function actionLiftBan($id)
    {
        $model = User::find()->hasId($id)->banned()->one();

        if (!empty($model)) {
            $model->status = Status::active();
            $model->save();
        }

        $this->redirect(['view', 'id' => $id]);
    }
}

backend/views/layouts/_menu.php
<?php
/** @noinspection PhpUnhandledExceptionInspection */

/**
 * @var $this View
 * @var $content string
 */

use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\web\View;

NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar navbar-expand-md fixed-top navbar-dark bg-dark',
    ],
]);
$menuItems = [];
if (!Yii::$app->user->isGuest) {
    // tournaments section
    if (Yii::$app->hasModule('tournaments')) {
        $subItems = [];
        
        $subItems[] = ['label' => Yii::t('app/backend', 'Tournaments'), 'url' => ['/tournaments/tournaments']];
        $subItems[] = ['label' => Yii::t('app/backend', 'Game Systems'), 'url' => ['/tournaments/game-system/index']];
        $subItems[] = ['label' => Yii::t('app/backend', 'Factions'), 'url' => ['/tournaments/faction/index']];
        
        if (!empty($subItems)) {
            $menuItems[] = [
                'label' => Yii::t('app/backend', 'Tournaments'),
                'items' => $subItems
            ];
        }
    }
    
    // разделы по работе с видео
    if (Yii::$app->hasModule('videos')) {
        $subItems = [];
        if (Yii::$app->user->can('backend/videos/view')) {
            $subItems[] = ['label' => Yii::t('app/backend', 'Videos'), 'url' => ['/video/video/index']];
            $subItems[] = ['label' => Yii::t('app/backend', 'Playlists'), 'url' => ['/video/playlist/index']];
        }
        if (!empty($subItems)) {
            $menuItems[] = [
                'label' => Yii::t('app/backend', 'Videos'),
                'items' => $subItems
            ];
        }
    }
    // разделы по работе с комьюнити
    if (Yii::$app->hasModule('community')) {
        if (Yii::$app->user->can('backend/news/view')) {
            $menuItems[] = ['label' => Yii::t('app/backend', 'News'), 'url' => ['/community/news/index']];
        }
    }
    
    // разделы по работе с аккаунтами и ролями
    $subItems = [];
    if (Yii::$app->user->can('backend/users/accounts/view')) {
        $subItems[] = ['label' => Yii::t('app/backend', 'Accounts'), 'url' => ['/user/index']];
    }
    if (Yii::$app->user->can('backend/users/roles/view')) {
        $subItems[] = ['label' => Yii::t('app/backend', 'Roles'), 'url' => ['/role/index']];
    }
    if (!empty($subItems)) {
        $menuItems[] = [
            'label' => Yii::t('app/backend', 'Users'),
            'items' => $subItems
        ];
    }
}
echo Nav::widget([
    'options' => ['class' => 'navbar-nav'],
    'items' => $menuItems,
]);

$menuItems = [];
if (Yii::$app->user->isGuest) {
    $menuItems[] = ['label' => Yii::t('app/backend', 'Log in'), 'url' => ['/site/login']];
} else {
    $menuItems[] = '<li>'
        . Html::beginForm(['/site/logout'], 'post')
        . Html::submitButton(
            Yii::t('app/backend', 'Log out ({username})', [
                'username' => Yii::$app->user->identity->username
            ]),
            ['class' => 'btn btn-link logout']
        )
        . Html::endForm()
        . '</li>';
}
echo Nav::widget([
    'options' => ['class' => 'navbar-nav ml-md-auto'],
    'items' => $menuItems,
]);
NavBar::end();

backend/views/layouts/main.php
<?php /** @noinspection PhpUnhandledExceptionInspection */

/**
 * @var $this View
 * @var $content string
 */

use backend\assets\AppAsset;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\bootstrap4\Html;
use yii\web\View;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->language ?>">
<head>
    <meta charset="<?php echo Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo Html::csrfMetaTags() ?>
    <title><?php echo Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="/favicon.png?v=0.1"/>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <?php echo $this->render('_menu') ?>

    <div class="container">
        <?php echo Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?php echo Alert::widget() ?>
        <?php echo $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?php echo Html::encode(Yii::$app->name) ?> <?php echo date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>