backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\forms\UserForm;
use backend\models\search\UserSearch;
use common\components\controllers\WebController;
use common\models\user\Status;
use Yii;
use common\models\user\User;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends WebController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'view'],
                        'roles'   => ['backend/users/accounts/view']
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['create'],
                        'roles'   => ['backend/users/accounts/create']
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['update', 'confirm', 'ban', 'lift-ban'],
                        'roles'   => ['backend/users/accounts/edit']
                    ]
                ]
            ]
        ];
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays a single User model.
     *
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new UserForm(['scenario' => UserForm::SCENARIO_CREATE]);

        if ($model->load(Yii::$app->request->post()) && $model->create()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = new UserForm(['scenario' => UserForm::SCENARIO_UPDATE]);
        $user = $this->findModel($id);
        $model->setUser($user);

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model
            ]);
        }
    }

    public function actionConfirm($id)
    {
        $model = User::find()->hasId($id)->one();

        if (!empty($model)) {
            $model->status = Status::active();
            $model->save();
        }

        $this->redirect(['view', 'id' => $id]);
    }

    public function actionBan($id)
    {
        $model = User::find()->hasId($id)->notBanned()->one();

        if (!empty($model)) {
            $model->status = Status::inactive();
            $model->save();
        }

        $this->redirect(['view', 'id' => $id]);
    }

    public function actionLiftBan($id)
    {
        $model = User::find()->hasId($id)->banned()->one();

        if (!empty($model)) {
            $model->status = Status::active();
            $model->save();
        }

        $this->redirect(['view', 'id' => $id]);
    }
}

frontend/controllers/PersonalController.php
<?php

namespace frontend\controllers;

use common\components\controllers\WebController;
use common\models\user\User;
use frontend\models\forms\UserEditForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class PersonalController
 *
 * @author Andreev Sergey <si.andreev316@gmail.com>
 * @version 1.0
 * @since 1.0
 */
class PersonalController extends WebController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'save-user-form', 'upgrade-account'],
                        'roles'   => ['@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['view']
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('login');
        }

        $user = User::findOne(Yii::$app->user->id);

        $userForm = new UserEditForm($user);

        return $this->render('index', [
            'user'     => $user,
            'userForm' => $userForm
        ]);
    }

    /**
     * @return array
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionSaveUserForm()
    {
        if(Yii::$app->request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;

            $user = User::findOne(Yii::$app->user->id);

            $model = new UserEditForm($user);

            if($model->load(Yii::$app->request->post()) && $model->update()){
                return [
                    'result' => 'success',
                    'html' => $this->renderAjax('_personalInfo', ['user' => $model->getUser()])
                ];
            }

            return [
                'result' => 'error',
                'errors' => $model->getErrors(),
                'html' => $this->renderAjax('_personalForm', ['userForm' => $model])
            ];
        } else{
            throw new NotFoundHttpException();
        }
    }

    /**
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     * @throws \Exception
     */
    public function actionUpgradeAccount()
    {
        if(Yii::$app->request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;

            $auth = Yii::$app->authManager;
            $vipRole = $auth->getRole('vip_customer');
            $auth->revokeAll(Yii::$app->user->id);

            return $auth->assign($vipRole, Yii::$app->user->id);
        } else{
            throw new NotFoundHttpException();
        }
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\components\controllers\WebController;
use common\models\user\Status;
use common\models\user\User;
use frontend\models\forms\RegisterForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\forms\LoginForm;
use frontend\models\forms\PasswordResetRequestForm;
use frontend\models\forms\ResetPasswordForm;

/**
 * Site controller
 */
class SiteController extends WebController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'register'],
                'rules' => [
                    [
                        'actions' => ['register'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index', []);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     * @throws \Exception
     */
    public function actionRegister()
    {
        $model = new RegisterForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->register()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * @param $token
     * @return string|\yii\web\Response
     */
    public function actionConfirmRegistration( $token ) {
        if ( ! empty( $token ) ) {
            $user = User::findByConfirmationToken( $token );
            if ( $user->isJustRegistered() ) {
                $user->status = Status::active();
                if ( $user->save() ) {
                    Yii::$app->user->login( $user, 3600 * 24 * 30 );
                    return $this->render( 'confirmRegistration', ['result' => 'success'] );
                }
            } elseif($user->isActive()) {
                return $this->render( 'confirmRegistration', ['result' => 'error', 'cause' => 'alreadyConfirmed'] );
            }
        }

        //return $this->goHome();
        return $this->render( 'confirmRegistration', [
        ] );
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = User::find()->andWhere(['email' => $model->email])->one();

            if (empty($user)) {
                return $this->render('requestPasswordResetToken', [
                    'result' => 'error',
                    'errorText' => Yii::t('app/frontend', 'There is no user with this email address.'),
                    'model' => $model,
                ]);
            }
            if ($user->isJustRegistered()) {
                return $this->render('requestPasswordResetToken', [
                    'result' => 'error',
                    'errorText' => Yii::t('app/frontend', 'User with this email is not confirmed. Confirm it by email or contact administration for help.'),
                    'model' => $model,
                ]);
            }

            if ($model->sendEmail()) {
                return $this->render('requestPasswordResetToken', ['result' => 'success', 'model' => $model]);
            } else {
                return $this->render('requestPasswordResetToken', [
                    'result' => 'error',
                    'errorText' => Yii::t('app/frontend', 'Sorry, we are unable to reset password for the provided email address.'),
                    'model' => $model,
                ]);
            }
        }

        return $this->render('requestPasswordResetToken', [
            'result' => '',
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     * @throws \yii\base\Exception
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            return $this->render('resetPassword', ['result' => 'success']);
        }

        return $this->render('resetPassword', [
            'result' => '',
            'model' => $model,
        ]);
    }
}

frontend/views/layouts/_menu.php
<?php
/** @noinspection PhpUnhandledExceptionInspection */

declare(strict_types=1);

use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\web\View;

/**
 * @var $this View
 * @var $content string
 */

NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl'   => Yii::$app->homeUrl,
    'options'    => [
        'class' => 'navbar navbar-expand-md fixed-top navbar-dark bg-dark',
    ],
]);

$menuItems = [];

if (Yii::$app->hasModule('tournaments')) {
    $menuItems[] = ['label' => Yii::t('app/frontend', 'Tournaments'), 'url' => ['/tournaments']];
}

// разделы по работе с видео
if (Yii::$app->hasModule('videos')) {
    $subItems = [];
    if (Yii::$app->user->can('backend/videos/view')) {
        $subItems[] = ['label' => Yii::t('app/frontend', 'Videos'), 'url' => ['/video/video/index']];
        $subItems[] = ['label' => Yii::t('app/frontend', 'Playlists'), 'url' => ['/video/playlist/index']];
    }
    if (!empty($subItems)) {
        $menuItems[] = [
            'label' => Yii::t('app/frontend', 'Videos'),
            'items' => $subItems
        ];
    }
}
// разделы по работе с комьюнити
if (Yii::$app->hasModule('community')) {
    $menuItems[] = ['label' => Yii::t('app/frontend', 'News'), 'url' => ['/community/news/index']];
}
if (Yii::$app->hasModule('outcomes')) {
    $menuItems[] = ['label' => Yii::t('app/frontend', 'Outcomes'), 'url' => ['/outcomes/calculator/index']];
}
// разделы по работе с аккаунтами
//$menuItems[] = ['label' => Yii::t('app/frontend', 'Users'), 'url' => ['/user/index']];

echo Nav::widget([
    'options' => ['class' => 'navbar-nav'],
    'items'   => $menuItems,
]);

$menuItems = [];
// ссылки на аккаунт
if (true) {
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => Yii::t('app/frontend', 'Registration'), 'url' => ['/site/register']];
        $menuItems[] = ['label' => Yii::t('app/frontend', 'Log in'), 'url' => ['/site/login']];
    } else {
        $menuItems[] = ['label' => Yii::t('app/frontend', 'Cabinet'), 'url' => ['/personal/index']];
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                Yii::t(
                    'app/frontend',
                    'Log out ({username})',
                    [
                        'username' => Yii::$app->user->identity->username
                    ]
                ),
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
}
echo Nav::widget([
    'options' => ['class' => 'navbar-nav ml-md-auto'],
    'items'   => $menuItems,
]);
NavBar::end();

frontend/views/layouts/main.php
<?php
/** @noinspection PhpUnhandledExceptionInspection */

declare(strict_types=1);

/**
 * @var $this View
 * @var $content string
 */

use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\web\View;
use frontend\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->language ?>">
<head>
    <meta charset="<?php echo Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo Html::csrfMetaTags() ?>
    <title><?php echo Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="/favicon.png?v=0.1"/>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <?php echo $this->render('_menu') ?>

    <div class="container">
        <?php echo Breadcrumbs::widget([
            'homeLink' => [
                'label' => '<i class="fas fa-home"></i>',
                'url' => '/',
                'encode' => false,
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?php echo \common\widgets\Alert::widget();?>
        <?php echo $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?php echo Html::encode(Yii::$app->name) ?> <?php echo date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>